"""
Read / write the worship data files that the static site consumes.

  js/songs-data.js   -> const LEGACY_SONGS = { "<slug>": {title, youtube, lyrics:[{label,lines}]}, ... };
  js/worship-songs.js -> window.WORSHIP_SETLIST = ['slug', ...];

songs-data.js is hand-authored JS (bare keys, \\' escapes, trailing comma). We parse it
tolerantly into plain dicts, and re-emit it byte-for-byte in the same house style so that
approving one song produces a minimal, reviewable diff.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SONGS_DATA_JS = REPO / "js" / "songs-data.js"
WORSHIP_SONGS_JS = REPO / "js" / "worship-songs.js"

_HEADER = (
    "// Legacy Bible Church — Hymnal Song Data\n"
    "// lyrics: populated as verified\n"
    "\n"
    "const LEGACY_SONGS = {\n"
)
_BARE_KEYS = ("title", "youtube", "lyrics", "label", "lines")


# ---------------------------------------------------------------- read


def _js_object_to_json(src: str) -> str:
    """Turn the LEGACY_SONGS object literal into strict JSON text."""
    # isolate the object literal
    start = src.index("{", src.index("LEGACY_SONGS"))
    end = src.rindex("}") + 1
    body = src[start:end]

    # quote the bare keys  ->  "title":
    body = re.sub(
        r'([{\[,\s])(' + "|".join(_BARE_KEYS) + r')\s*:',
        lambda m: f'{m.group(1)}"{m.group(2)}":',
        body,
    )
    # \' is not valid JSON; a literal apostrophe is fine inside a JSON string
    body = body.replace("\\'", "'")
    # drop trailing commas:  ,}  ,]
    body = re.sub(r",(\s*[}\]])", r"\1", body)
    return body


def load_songs() -> dict:
    """slug -> {title, youtube, lyrics:[{label, lines:[...]}, ...]}"""
    raw = SONGS_DATA_JS.read_text(encoding="utf-8")
    return json.loads(_js_object_to_json(raw))


def load_setlist() -> list[str]:
    raw = WORSHIP_SONGS_JS.read_text(encoding="utf-8")
    m = re.search(r"WORSHIP_SETLIST\s*=\s*(\[.*?\])", raw, re.S)
    if not m:
        return []
    arr = re.sub(r",(\s*\])", r"\1", m.group(1)).replace("'", '"')
    return json.loads(arr)


# ---------------------------------------------------------------- write


def _emit_str(s: str) -> str:
    # double-quoted JS string; apostrophes are left literal (valid, and keeps
    # future approval diffs small once the file is normalised once up front)
    body = s.replace("\\", "\\\\").replace('"', '\\"')
    return '"' + body + '"'


def _emit_song(slug: str, song: dict) -> str:
    out = [f'  {_emit_str(slug)}: {{']
    out.append(f'    title: {_emit_str(song["title"])},')
    out.append(f'    youtube: {_emit_str(song.get("youtube", ""))},')
    out.append("    lyrics: [")
    blocks = []
    for b in song["lyrics"]:
        lines = ", ".join(_emit_str(x) for x in b["lines"])
        blocks.append(f'    {{ label: {_emit_str(b.get("label", ""))}, lines: [{lines}] }}')
    out.append(",\n".join(blocks))
    out.append("  ]")
    out.append("  }")
    return "\n".join(out)


def dump_songs(songs: dict) -> None:
    """Write songs-data.js in the repo's house style (keys kept in file order)."""
    parts = [_emit_song(slug, songs[slug]) for slug in songs]
    SONGS_DATA_JS.write_text(_HEADER + ",\n".join(parts) + ",\n};\n", encoding="utf-8")


def upsert_song(slug: str, *, title: str, youtube: str, lyrics: list[dict]) -> None:
    songs = load_songs()
    songs[slug] = {"title": title, "youtube": youtube, "lyrics": lyrics}
    dump_songs(songs)


def write_setlist(slugs: list[str], sunday: str | None = None) -> None:
    dated = f"\n * Sunday {sunday}\n" if sunday else "\n"
    body = "".join(f"  '{s}',\n" for s in slugs)
    WORSHIP_SONGS_JS.write_text(
        "/**\n"
        " * LBC Sunday Setlist\n"
        " * ──────────────────\n"
        " * Generated by scripts/prep from the approved rows of the setlist sheet.\n"
        f" *{dated}"
        " */\n"
        "\n"
        f"window.WORSHIP_SETLIST = [\n{body}];\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    # round-trip self check
    import sys

    songs = load_songs()
    print(f"parsed {len(songs)} songs; setlist = {load_setlist()}", file=sys.stderr)
    if "--check" in sys.argv:
        before = SONGS_DATA_JS.read_text(encoding="utf-8")
        dump_songs(songs)
        after = SONGS_DATA_JS.read_text(encoding="utf-8")
        SONGS_DATA_JS.write_text(before, encoding="utf-8")  # restore
        import difflib

        diff = list(
            difflib.unified_diff(before.splitlines(), after.splitlines(), "before", "after", lineterm="")
        )
        if diff:
            print("\n".join(diff[:80]))
            print(f"... {len(diff)} diff lines" if len(diff) > 80 else "")
        else:
            print("round-trip identical ✓")
